### PR TITLE
Added compatibility with ComfyUI-Easy-Use sampler and loader

### PR DESCRIPTION
**Pull request by Hapseleg**
Hi,

I added ComfyUI-SaveImageWithMetaData\py\defs\ext\easyuse_nodes.py which adds the ability to use nodes from https://github.com/yolain/ComfyUI-Easy-Use 
easy fullLoader, easy comfyLoader, easy fullkSampler and easy loraStack,

You can load this workflow to test it:
workflow (5)

I also added the ability to use the Lora built into the Loader, you could copy paste that to efficiency_nodes.py if you want to.

### CODE REVIEW

**Comment by nkchocoai** [comment]
Thanks for your PR.

**Comment by Hapseleg** [comment]
Hey, I noticed a small thing that should be changed, the Lora stacker has a toggle and when its off it will still add the loras to the metadata, but its a easy fix, check this commit i made:
https://github.com/nkchocoai/ComfyUI-SaveImageWithMetaData/commit/2ff7d494d7d1cdf1e3ec70dfc223d70a11359002

image

**Comment by EnragedAntelope** [comment]
I tried this and like the functionality, thank you. But I am wondering, why does it take so much time for the last node (image saver) to execute? I think the image was already decoded by that point, and even then a vae decode doesn't take that long normally. Is there any opportunity to optimize?

**Comment by Hapseleg** [comment]
> I tried this and like the functionality, thank you. But I am wondering, why does it take so much time for the last node (save image with metadata) to execute? I think the image was already decoded by that point, and even then a vae decode doesn't take that long normally. Is there any opportunity to optimize?

Oh yeah now that you mentioned it that's actually true.. I'll look into it

**Comment by Hapseleg** [comment]
I tested a bit, I disabled the easy-use extension and removed my file from ComfyUI-SaveImageWithMetaData\py\defs\ext but everytime i change to a new checkpoint the first save takes about 5 seconds so it seems its not related to my PR?

**Comment by EnragedAntelope** [comment]
Thanks. I hadn't used this extension before so don't know source of the issue. It seemed to take long even with the same checkpoint selected and being used multiple times in a row.

**Comment by nkchocoai** [comment]
@EnragedAntelope
> But I am wondering, why does it take so much time for the last node (save image with metadata) to execute?

It is taking a long time to hash the checkpoint.
However, this time is reduced the second time and thereafter because the cache is used.
https://github.com/nkchocoai/ComfyUI-SaveImageWithMetaData/blob/master/py/utils/hash.py#L7-L18

**Comment by Hapseleg** [comment]
> @EnragedAntelope
> 
> > But I am wondering, why does it take so much time for the last node (save image with metadata) to execute?
> 
> It is taking a long time to hash the checkpoint. However, this time is reduced the second time and thereafter because the cache is used. https://github.com/nkchocoai/ComfyUI-SaveImageWithMetaData/blob/master/py/utils/hash.py#L7-L18

So I guess we should save the hash instead of doing it everytime... I'll copy the way a1111 does it, might as well keep a standard and be able to load the hashes a1111 saved :)

**Pull request merged**
